# Generated by Django 4.0.1 on 2023-05-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('0', 'featured'), ('1', 'normal')], max_length=50)),
                ('fram', models.CharField(choices=[('0', 'django'), ('1', 'flask'), ('2', 'featured')], max_length=50)),
                ('thumbnail', models.ImageField(upload_to='media')),
                ('body', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
